# Generated by Django 5.1.5 on 2025-01-29 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIcatalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tag',
            new_name='tags',
        ),
    ]
