# Generated by Django 5.1.5 on 2025-02-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIcatalog', '0005_alter_product_brand_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
